### ISSUE TITLE
Create competition user - missing mentor error

### ISSUE THREAD

**Issue by mihak** [polz113/bober#2]
As super user (sysadmin) - if not super user, creating new user is not possible.

Create competition user form does not have dropdown for mentor. 
![image](https://cloud.githubusercontent.com/assets/7932199/4783313/f1c14e5e-5d20-11e4-9eac-6266244b1460.png)

If trying to save, error is thrown, but record still exists in table:
![missingmentorerror](https://cloud.githubusercontent.com/assets/7932199/4783317/28eb498e-5d21-11e4-95c0-b7a5d36454e4.png)

This also leads to error when logged in as teacher when trying to show competition users:
![missingmentorasteacher](https://cloud.githubusercontent.com/assets/7932199/4783320/7666fc6c-5d21-11e4-933f-c2bf28cceba1.png)

**Comment by polz113** [comment]
This is an issue with the old, unmaintained system.
